language: ruby
rvm:
  - 2.2
before_script:
  - gem install awesome_bot
script:
  - awesome_bot README.md --allow-dupe --allow-redirect --allow-ssl --white-list https://magesec.org,https://opensource.magento.com/contribution-day-handbook
