name: Check Links Health

on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron:  '0 1 * * 0' # * is a special character in YAML so you have to quote this string

jobs:
  check-links-health:    
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby 2.7.1
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.1
    - name: Run awesome_bot
      run: |
           gem install awesome_bot
           awesome_bot README.md --request-delay 1 --allow-dupe --allow-ssl --allow-redirect --white-list https://commercemarketplace.adobe.com/,https://www.reddit.com/r/Magento/,https://business.adobe.com/summit/adobe-summit.html,https://support.magento.com/hc/en-us/categories/360004245632-Support-Tools,https://business.adobe.com/resources/main.html?Products+%26+Services=Commerce,https://business.adobe.com/blog/tags/commerce,https://helpx.adobe.com/security.html,https://www.goodreads.com/book/show/52703436-magento-2,https://belvg.com/blog/,https://www.linkedin.com/pulse/automatically-create-magentos-cspwhitelistxml-file-kieckbusch-stlqc/
    - name: Create issue on awesome_bot fail            
      if: ${{ failure() }}   
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}        
      run: |
           echo -n 'gh issue create --title ' > gh-issue.create.sh
           echo -n `cat ab-results-README.md-markdown-table.json | jq '.title'` >> gh-issue.create.sh
           echo -n ' --body ' >> gh-issue.create.sh
           echo `cat ab-results-README.md-markdown-table.json | jq '.message'` >> gh-issue.create.sh           
           sed -i 's/`/\\`/g' gh-issue.create.sh
           sed -i 's/\\n/\n/g' gh-issue.create.sh
           sh gh-issue.create.sh
