name: Update extensions_generated_for_gpt.csv
on: [workflow_dispatch, push, pull_request]
jobs:
  update-readme:
    name: Update extensions_generated_for_gpt.csv
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run csv generator
        run: |
          php csv2gpt.php resources.csv extensions_generated_for_gpt.csv
          git config user.name "GitHub Actions"
          git config user.email github-actions@github.com
          if [[ `git status --porcelain` ]]; then git add . && git commit -m "extensions.csv updated by action" && git push; fi
